import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col ">

       
        
        <nav className=" w-ull h-16 bg-foreground text-background grid grid-cols-3 items-center px-8 ">
          <div className="justify-self-start flex items-center gap-2">
            <Image
            src="/background-removed.png"
            alt="Next.js Logo"
            width={110}
            height={110}
            className="object-contain"
          />

          </div>
                    
          <div className="font-semibold flex gap-8 justify-self-center">


            
            <Link href={"/"} className=" px-4  py-2 rounded-xl text-amber-50  bg-gray-500 transition delay-150 duration-300 ease-in-out hover:-translate-y-2 hover:scale-110 hover:bg-indigo-900">Home</Link>
            <Link href={"/about"} className=" px-4  py-2 rounded-xl text-amber-50  bg-gray-500 transition delay-150 duration-300 ease-in-out hover:-translate-y-2 hover:scale-110 hover:bg-indigo-900">About</Link>
            <Link href={"/notes"} className=" px-4  py-2 rounded-xl text-amber-50  bg-gray-500 transition delay-150 duration-300 ease-in-out hover:-translate-y-2 hover:scale-110 hover:bg-indigo-900">Notes</Link>
            <Link href={"/contact"} className=" px-4  py-2 rounded-xl text-amber-50  bg-gray-500 transition delay-150 duration-300 ease-in-out hover:-translate-y-2 hover:scale-110 hover:bg-indigo-900">Contact</Link>
          </div>
        </nav>
         

        {children}

      </body>
    </html>
  );
}


