import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col  ">
        <nav className="bg-[url(/fondonav.webp)] bg-cover  bg-no-repeat">
          <div className="bg-black/15 w-full h-full  text-background grid grid-cols-3 items-center px-8 ">
            <div className="justify-self-start flex items-center gap-2">
              <Image
                src="/background-removed.png"
                alt="Next.js Logo"
                width={110}
                height={110}
                className="object-contain"
              />
            </div>

            <div className="font-semibold flex gap-8 justify-self-center">
              <Link
                href={"/"}
                className="  px-4  py-2 rounded-xl text-amber-50  bg-gray-500/50 transition delay-150 duration-300 ease-in-out hover:-translate-y-2 hover:scale-110 hover:bg-indigo-900/50"
              >
                Home
              </Link>
              <Link
                href={"/about"}
                className=" px-4  py-2 rounded-xl text-amber-50  bg-gray-500/50 transition delay-150 duration-300 ease-in-out hover:-translate-y-2 hover:scale-110 hover:bg-indigo-900/50"
              >
                About
              </Link>
              <Link
                href={"/notes"}
                className=" px-4  py-2 rounded-xl text-amber-50  bg-gray-500/50 transition delay-150 duration-300 ease-in-out hover:-translate-y-2 hover:scale-110 hover:bg-indigo-900/50"
              >
                Notes
              </Link>
              <Link
                href={"/contact"}
                className=" px-4  py-2 rounded-xl text-amber-50  bg-gray-500/50 transition delay-150 duration-300 ease-in-out hover:-translate-y-2 hover:scale-110 hover:bg-indigo-900/50"
              >
                Contact
              </Link>
            </div>
          </div>
        </nav>

        {children}

        <footer className="pt-5 border-t border-white/10 flex  justify-between gap-10">
          <div className=" p-8 flex gap-8 text-gray-400 text-sm font-medium">
            <div className="flex flex-col">
              <span className="text-white text-xl font-bold">100%</span>
              <span>Compromiso</span>
            </div>
            <div className="flex flex-col">
              <span className="text-white text-xl font-bold">Next.js</span>
              <span>Tecnología</span>
            </div>
          </div>
          <div className="flex flex-col py-7 ">
            <h1>No dude en usar nuesta Pagina</h1>
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-blue-200 to-red-600">
              Todos los derechos reservados a aballo.inc
            </span>
          </div>

          <div>
            <div className="bg-white rounded-full  py-6 px-6">
              <Image
                src="/nextjs-svgrepo-com.svg"
                alt="Next.js Logo"
                width={60}
                height={60}
                className="object-contain"
              />
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
